# Generated by Django 2.1.1 on 2018-09-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_room_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='active',
        ),
        migrations.AddField(
            model_name='room',
            name='number_of_connected',
            field=models.IntegerField(default=0),
        ),
    ]
