# Generated by Django 2.1.1 on 2018-09-14 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20180914_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='lefinstance',
            name='size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='current_instance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.LEFInstance'),
            preserve_default=False,
        ),
    ]
