# Generated by Django 2.1.1 on 2018-09-14 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20180914_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='current_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.LEFInstance'),
        ),
    ]
