# Generated by Django 2.1.1 on 2018-09-15 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20180914_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='room',
            name='number_of_connected',
        ),
        migrations.AddField(
            model_name='player',
            name='connected_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_players', to='game.Room'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
