# Generated by Django 2.1.1 on 2018-09-15 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20180915_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leforder',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefs', to='game.LEFInstance'),
        ),
    ]
